export const INTRO_CLASS_CATALOG_OBJECT_ID = process.env.INTRO_CLASS_CATALOG_OBJECT_ID!;
export const DROP_IN_CATALOG_OBJECT_ID = process.env.DROP_IN_CATALOG_OBJECT_ID!;
export const MONTHLY_SUBSCRIPTION_CHECKOUT_URL = process.env.MONTHLY_SUBSCRIPTION_CHECKOUT_URL!;